### ISSUE TITLE
Will there be an APK release soon?

### ISSUE THREAD

**Issue by ghost** [iTaysonLab/jetispot#1]
Will there be an APK release soon or i need to build myself?

**Comment by iTaysonLab** [comment]
at the current moment - nope, bcs it is not usable (playback is only for one track, but the auth/browser are working fine)

after rewriting the player to media2 I will push the release APKs

**Comment by ghost** [comment]
Sure, would love a FOSS player for spotify.

**Comment by iTaysonLab** [comment]
welp, it came: https://github.com/iTaysonLab/jetispot/releases/tag/v1_poc

very broken, but at least it can play music
