### ISSUE TITLE
Redesigned Now Playing / playing forwards

### ISSUE THREAD

**Issue by Taker18** [iTaysonLab/jetispot#18]
Hey there, V11 with the redesigned Now Playing looks horrible. It's just a blank screen with a small album art. 
The Media Control Line where you can move the song back / forward is also not working. 

Keep Up the good work!!!

**Comment by iTaysonLab** [comment]
layout won't be changed (for now), but:
- sizes of elements might be changed in the future
- it's intended to be "empty" for future features to fit properly (lyrics for example)
- seekbar is not yet implemented (with like button), so it is not reacting to actions

**Comment by Taker18** [comment]
Thank you for the Information! 

Appreciate it!
