### ISSUE TITLE
Songs ain't playing 

### ISSUE THREAD

**Issue by MrConqueror** [iTaysonLab/jetispot#19]
I downloaded the app log in my Spotify account then Picked a song but there's no sounds

**Comment by iTaysonLab** [comment]
Do you have Spotify Premium account?

Just in case: this app WON'T work properly with free accounts (as stated in README) and this won't be fixed.

**Comment by Pinguin2001** [comment]
@MrConqueror Select normal audio quality and it should work fine (at least it does for me)

**Comment by boehs** [comment]
@Pinguin2001 confirmed to be working, thank you!
