### ISSUE TITLE
Never Logs In

### ISSUE THREAD

**Issue by itchangesshape** [iTaysonLab/jetispot#20]
The app stays still and does notching each time I try to login.  I have Premium, using the right creds, no VPN or anything. The Android 13 Media Player appears in the notification shade, but that's it.

**Comment by iTaysonLab** [comment]
seems like a librespot-java issue, it tries to connect to the servers and stays for a long time, I have seen no known workaround for that

after logging in, when you force stop application and launch it again, it will ask for creds or stuck on a fullscreen loading spinner?

**Comment by itchangesshape** [comment]
Actually...that made it work! Clicked log in - Force stop - Reopen - Took me to my home page!
