### ISSUE TITLE
App has no point other than Material Design

### ISSUE THREAD

**Issue by fabioromeo** [iTaysonLab/jetispot#30]
Sorry, but a third party client has to bring something new, preferably better, to the table. The app just replicates the atrocious design of the original client with less features and a Material You varnish. Why bother then?

Spotify needs better playlist and music management, better podcast isolation from the music, and a way to block unwanted playlists, artists and songs. If Jetispot could bring those, then now we're talking.

**Comment by iTaysonLab** [comment]
you know, I don't really know why I am doing such stuff

**Comment by fabioromeo** [comment]
Ouch. Sorry, I didn't mean to be such a downer... The app is completely valid as a personal study or personal development. I'm just saying that it could have more features to set itself apart from the other - specially the original one which is pretty bad... Just having a better playlist management would make it leagues ahead the main app. 

Again, sorry if my comment was harsh, this was not what I meant.

**Comment by jakiisheep** [comment]
Not meaning to argue or offend you, but @fabioromeo, if this app is not useful to you, or you think its "unneeded" or that it has to offer more features then why not move on with your life, find a new client, I dont know? Why comment just to bring the dev's motivation down?

The app is here to prove that a Material You client is possible - design is important these days, the app dev never said he will bring any "new features" like playlist management, which is not even possible (or possible but really hard) without spotify implementing it

**Comment by iTaysonLab** [comment]
Personally, I don't care about these posts. 

As I have stated before, I completely have no idea why I am doing these projects (because of very narrow user base), but at least this is still interesting for me.

Closing the issue because there is no actual point in these discussions - it can take forever.

P.S: playlist management is possible, but I'm now focused on Jetisteam (heh, I need to rename that).

**Comment by jakiisheep** [comment]
> Personally, I don't care about these posts.
> 
> As I have stated before, I completely have no idea why I am doing these projects (because of very narrow user base), but at least this is still interesting for me.
> 
> Closing the issue because there is no actual point in these discussions - it can take forever.
> 
> P.S: playlist management is possible, but I'm now focused on Jetisteam (heh, I need to rename that).

Ah, okay, I just wanted to stop people from brining developers' motivations down, even if a project is "stupid", it's still useful to you, and you should continue working on it

Btw, on that topic, do you know the difference between this (og version) of jetispot and [BobbyESP's fork](https://github.com/BobbyESP/Jetispot/)? I came across the fork and now this repo from reddit

**Comment by iTaysonLab** [comment]
> this (og version) of jetispot and [BobbyESP's fork](https://github.com/BobbyESP/Jetispot/)?

OTA, some fixes, improvements, etc - you can see the commits in the PR

**Comment by jakiisheep** [comment]
Thanks! Have a good rest of your night/day/morning!

**Comment by lorenzholzbauer** [comment]
I love material design so I really appreciate your work on the project
