### ISSUE TITLE
Don't log in

### ISSUE THREAD

**Issue by EgordevG** [iTaysonLab/jetispot#32]
At the entrance, it says that I need a premium, although it is, I turn on VPN and when I log in to my account, it says that the login and password are incorrect

**Comment by linesquarecube** [comment]
Hi, I have been automatically logged out of the previous version 2 days ago and cannot re-login. Have already cleared cache / user data and reinstalled the app. Unfortunately still the same issue. Is there perhaps a issue with Spotify?

**Comment by pablo03v** [comment]
Same here

**Comment by cristiangutie** [comment]
Same here, premium account and it says that I need "premium account".

**Comment by MadCat9958** [comment]
Same here

**Comment by SuperDog34** [comment]
I have the same problem![IMG_20230624_122918.jpg](https://github.com/iTaysonLab/jetispot/assets/51761543/0ab7856b-7025-46d2-aa70-7fdc4c12d7b0)

**Comment by algatern** [comment]
I am also having the same issue.

**Comment by sseaan** [comment]
Same here

**Comment by ChristianNewton** [comment]
I am also having that issue.

**Comment by ShadowAya** [comment]
Unfortunately the same issue here, I first assumed it was related to being on the Family plan

**Comment by iTaysonLab** [comment]
sorry for the long wait

investigating the issue, but I don't know ETA for this

**Comment by BobbyESP** [comment]
> sorry for the long wait
> 
> investigating the issue, but I don't know ETA for this

Updating your private fork of librespot-java would be enough

**Comment by ghost** [comment]
Can vouch!

**Comment by thang-qt** [comment]
+1 for this

**Comment by fxzxmicah** [comment]
Same problem with incorrect username or password. But it's normal to login to the official website.

**Comment by CaoilainnFW** [comment]
Is there any news on this bug? I've got premium and I'd really like to be able to use the app

**Comment by BobbyESP** [comment]
In the telegram of Tayson there is a release with the login fixed

**Comment by iTaysonLab** [comment]
> Is there any news on this bug? I've got premium and I'd really like to be able to use the app

I forgot to publish a fixed release to GitHub. My bad :(

ETA: 24 hours.

**Comment by fxzxmicah** [comment]
I don't know why, but I still can't log in, and I'm prompted with the wrong username or password.
