### ISSUE TITLE
Can't sign in with Premium Family

### ISSUE THREAD

**Issue by LordImmaculate** [iTaysonLab/jetispot#33]
I can't sign in with Premium Family. I am not the one who pays. It says "You need Spotify Premium to use JeriSpot"

**Comment by 0lle0nline** [comment]
I'm having the same issue on Pixel 6a running GrapheneOS

**Comment by utada1stlove** [comment]
same on oneplus8 running OOS

**Comment by iTaysonLab** [comment]
Duplicate of #32 :(
